#23 Add rule that dummy arguments should have specified intent
MetOffice/stylist pull request #41
Opened 2022-03-11 18:09 UTC by bilal-chughtai

Implemented rule outlined in #23, along with some unit and system testing. I note that some of the code blocks the unit test produces while checking all permutations are invalid fortran, specifying for example two or no `intent(out)` variables for a function. I think this is fine, since the compiler will catch these issues, and logic for preventing this complicates the unit test unnecessarily, and is beyond the scope of the rule. This rule won't work find subroutines or functions that don't reside within a `program` or `module`, which is a property I'm aware some legacy code can exhibit. I'm leaving this as a known shortcoming. Closes #23.

2022-03-23 13:03 UTC, MatthewHambley requested changes
Looks good. A report on using the rule on a sample codebase, such as LFRic, would be good evidence of function.

2022-03-24 16:45 UTC, bilal-chughtai commented on source/stylist/fortran.py
> +                unit_type = 'function'
moved.

2022-03-24 16:48 UTC, bilal-chughtai commented on source/stylist/fortran.py
> +                    # that's all we need
elaborated

2022-03-25 11:56 UTC, bilal-chughtai commented on source/stylist/fortran.py
> +            for spec in specs.children:
Things fall over. The only way I can see this happening is if you declare a subprogram and put nothing in it, as the specification part is the first thing fparser looks for.

```
subroutine foo(bar)
end subroutine blah
```
I'll add some logic and a test to deal with this appropriately.

2022-03-25 13:58 UTC, bilal-chughtai commented on source/stylist/fortran.py
> +                                        dummy_args.remove(arg_name.lower())
This does however make testing harder - the ordering of iteration over a list is unpredictable. I think I'll keep the original.

2022-03-28 14:14 UTC, MatthewHambley requested changes
Just two minor things to finish and then it's off to the races.

2022-03-28 14:14 UTC, MatthewHambley commented on system-tests/fortran/missing_intent.f90
> +      logical, intent(inout):: qux
Did this get forgotten?

2022-03-28 14:14 UTC, MatthewHambley commented on system-tests/fortran/missing_intent.f90
> +end module test_module
Now that the rule supports procedure program units they should be tested here.

2022-03-28 15:11 UTC, merged